### ISSUE TITLE
[DEV] Add wallet list screen

### ISSUE THREAD

**Issue by pandafliesinspace** [virustyt/FinanceAdvisor#3]
Ass an APP USER, I WANT to open an app and see the initial wallet list screen(no wallets state).

Add wallet button CTA is not clickable(out of scope of this issue)
Theme can be random

![Screenshot 2021-12-24 at 12 55 06](https://user-images.githubusercontent.com/26408366/147342495-2f515241-8412-4ffe-aada-044817c55c04.png)

**Comment by virustyt** [comment]
take issue, aproximate time 1 hour

**Comment by virustyt** [comment]
done. #11
